apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: winfotest-os
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: winfotest2-dev-vault
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: wt-dev-db-credentials
        property: host
    - secretKey: password
      remoteRef:
        key: wt-dev-db-credentials
        property: password
    - secretKey: port
      remoteRef:
        key: wt-dev-db-credentials
        property: port
    - secretKey: user
      remoteRef:
        key: wt-dev-db-credentials
        property: user
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: winfotest-os
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: winfotest2-dev-vault
    kind: ClusterSecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: encryption_key
      remoteRef:
        key: wt-dev-app-secrets
        property: encryption_key
    - secretKey: oracle_erp_url
      remoteRef:
        key: wt-dev-app-secrets
        property: oracle_erp_url
    - secretKey: kafka_bootstrap
      remoteRef:
        key: wt-dev-app-secrets
        property: kafka_bootstrap